### PR TITLE
set_iaq_humidity

### PR DESCRIPTION
**Pull request by Dmole**
set_iaq_humidity

### CODE REVIEW

**Comment by ladyada** [comment]
hiya, thanks for the PR! please fix the travis complaint (its a small pylint fix) and if you could, also include an example script that shows how people could use this capability - that would be amazing :)

**Comment by caternuson** [comment]
Is this also readable? If so, add a getter and then also provide `@property` style access for both. You can have those simply call your getter/setter funcs. This will allow the syntax below.

To set:
```python
sgp30.iaq_humidity = 23.0
```
To query:
```python
print(sgp30.iaq_humidity)
```

**Comment by Dmole** [comment]
> Is this also readable? ...

Not according to the top of page 10;
https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/0_Datasheets/Gas/Sensirion_Gas_Sensors_SGP30_Datasheet.pdf

**Comment by Dmole** [comment]
> ...example script that shows how people could use this capability...

Sampling every second is required to prevent endless clime of SGP30 values but `time.sleep(1)` is sub optimal because it does not account for operation time and non-real-time-operating-systems, but python is bloated so I may port the code before correcting the timing.

To use the humidity one must convert it from relative-humidity to grams (otherwise SGP30 values go crazy);

```
def rh2gpm3(temp, relativeHumidity, pres):
	kuniv = 8.314472471220217
	MH2O = 18.01534
	airdens = pres * 100.0 / kuniv / (temp + 273.15)
	psat = h2opsat(temp)
	ph2o = psat * relativeHumidity / 100
	vmr = ph2o / pres
	a = vmr * MH2O * airdens
	return a 

def h2opsat(t):
	pwat = 6.107799961 + t * (4.436518521e-1 + t * (1.428945805e-2 + t * (2.650648471e-4 + t * (3.031240396e-6 + t * (2.034080948e-8 + t * 6.136820929e-11)))))
	pice = 6.109177956 + t * (5.034698970e-1 + t * (1.886013408e-2 + t * (4.176223716e-4 + t * (5.824720280e-6 + t * (4.838803174e-8 + t * 1.838826904e-10)))))
	return min(pwat, pice)
```

That code was ported from https://www.cactus2000.de/uk/unit/pophum.shtml

While on the path to accuracy it's worth restoring the baseline which can be done by tailing the log;

```
import subprocess
def stail(f, n=10):
	proc = subprocess.Popen(['tail', '-n', str(n), f], stdout=subprocess.PIPE)
	return proc.stdout.readlines()
```

but python lacks this functionality (maybe there is some popular lib?) so for windows a longer (untested and copied from stackoverflow) solution;

```
def tail( f, lines=20 ):
	total_lines_wanted = lines
	BLOCK_SIZE = 1024
	f.seek(0, 2)
	block_end_byte = f.tell()
	lines_to_go = total_lines_wanted
	block_number = -1
	blocks = []
	while lines_to_go > 0 and block_end_byte > 0:
		if (block_end_byte - BLOCK_SIZE > 0):
			# read the last block we haven't yet read
			f.seek(block_number*BLOCK_SIZE, 2)
			blocks.append(f.read(BLOCK_SIZE))
		else:
			f.seek(0,0)
			blocks.append(f.read(block_end_byte))
		lines_found = blocks[-1].count('\n')
		lines_to_go -= lines_found
		block_end_byte -= BLOCK_SIZE
		block_number -= 1
	all_read_text = ''.join(reversed(blocks))
	return '\n'.join(all_read_text.splitlines()[-total_lines_wanted:])
```

The actual loop I am using at the moment looks like;


```
import adafruit_sgp30
import adafruit_sht31d
import datetime
import logging
import os.path
import re

f = '/var/log/sgp30.log'

def initLog(f):
	logging.basicConfig(filename=f, format='%(message)s', level=logging.DEBUG)

i2c = BUSIO()
sht31d = adafruit_sht31d.SHT31D(i2c)
sgp30 = adafruit_sgp30.Adafruit_SGP30(i2c)
#print("SGP30  serial #", [hex(i) for i in sgp30.serial])
#print("SHT31D serial #", [hex(i) for i in sht31d.serial])
if os.path.isfile(f):
	L = str(stail(f, n=1)[0])
	L = re.sub(r'\\.*', '', L)
	L = re.sub(r'^([^,]+),([^,]+),([^,]+),([^,]+),([^,]+),', '', L)
	BC = re.sub(r'([^,]+),([^,]+)', r'0x\1', L)
	BV = re.sub(r'([^,]+),([^,]+)', r'0x\2', L)
	BC = int(BC, 16)
	BV = int(BV, 16)
	sgp30.set_iaq_baseline(BC, BV)
	initLog(f)
else:
	initLog(f)
	logging.info("datetime,eCO2-ppm,TVOC-ppb,humidity-%,temperature-C,baseline-eCO2,baseline-TVOC")
elapsed_sec = 0
while True:
	if elapsed_sec >= 60:
		elapsed_sec = 0
		d = datetime.datetime.utcnow().replace(microsecond=0).isoformat()
		pres = 1013.25
		rh = rh2gpm3(sht31d.temperature, sht31d.relative_humidity, pres)
		sgp30.set_iaq_humidity(rh)
		logging.info("%s,%d,%d,%f,%f,%x,%x" % (d, sgp30.eCO2, sgp30.TVOC, sht31d.relative_humidity, sht31d.temperature, sgp30.baseline_eCO2, sgp30.baseline_TVOC))
		sht31d.heater = True
	else:
		if elapsed_sec == 1:
			sht31d.heater = False
		sgp30.eCO2
	time.sleep(1)
	elapsed_sec += 1
```

Note that atmospheric pressure is hard coded so use the internet or get another sensor to improve that. Logging every minute is enough data for my use case. I'm not sure how often `sht31d.heater` should be used but I'm assuming 1s after every 60s read is OK (because it's so small and the sensor is stabilize at that time when compared to other sensors). Some classes like i2c/BUSIO may have different names upstream due to the 2 bugs I previously reported which I assume are fixed but because pip3 has no upgrade command I may port away from python first... or not depending on laziness.
Output looks something like;

```
datetime,eCO2-ppm,TVOC-ppb,humidity-%,temperature-C,baseline-eCO2,baseline-TVOC
2019-01-08T16:24:54,454,145,48.846970,18.858244,84dd,8a7f
2019-01-08T16:26:00,467,162,49.268196,18.858244,84dd,8a7f
2019-01-08T16:27:06,441,151,49.039269,18.831540,84dd,8a7f
2019-01-08T16:28:11,484,164,49.327717,18.874266,84dd,8a7f
2019-01-08T16:29:17,442,151,49.019428,18.874266,84dd,8a7f
2019-01-08T16:30:23,432,157,49.039269,18.844892,84dd,8a7f
2019-01-08T16:31:29,447,154,48.952276,18.831540,84dd,8a7f
2019-01-08T16:32:35,432,146,48.924805,18.815518,84dd,8a7f
2019-01-08T16:33:41,456,154,49.143049,18.815518,84dd,8a7f
2019-01-08T16:34:47,471,156,49.216306,18.914321,84dd,8a7f
```

There are some tests that would quantify how the measured variables effect each other... I might get around to that.

**Comment by caternuson** [comment]
Bummer it's not readable. OK, then at least add a property setter to allow:
```python
sgp30.iaq_humidity = 23.0
```
One idea - the value could be stored locally. And have that value init'd to the POR default of 11.57 g/m3. Update the value in the setter. Then simply return its current value for the getter:
```python
print(sgp30.iaq_humidity)
```
Not ideal. If you ran a program that set it, then quit that program and started another one, it would not know the actual value. So might also make sense to push the default value out in `__init__` so it's set to something known.

And for now, I'd suggest just having this take in the expected absolute humidity in g/m3. Update the doc string to reflect this. Then the functionality is at least in place. Adding additional functions to allow setting this in terms of relative humidity can be done later or elsewhere.

**Comment by Dmole** [comment]
> ...the [humidity] value could be stored [in adafruit_sgp30]...

The "Unix philosophy of small sharp tools" and "KISS principle" compels me to want to leave adafruit_sgp30 as a simple get/set wrapper. Otherwise I'd want the whole read every second loop in adafruit_sgp30 to make it a friendly API, not an in between monster. 

> ... push the default value ...

That would prevent disabling the onchip humidity compensation without disabling the onchip calibration. I would wager the value is reset by the adafruit_sgp30 constructor calling onchip init anyway.

> ...Adding additional functions to allow setting this in terms of relative humidity can be done later or elsewhere.

Yes I was just answering ladyada's request for an example.

**Comment by ladyada** [comment]
i think it's good as is - cacheing it makes it seem like you're actually able to read the value. i think this is good to go. one day, having an example that goes with a standard humidity sensor would be nice - the DS mentions the SHT series :)

**Comment by caternuson** [comment]
Looks good. Thanks for updating the humidity name and units.

Bummer this isn't readable. Would be nice to have some way to check its current setting if your were ever wondering about odd readings. But my suggestions are also pretty hack-ish, so not ideal. Guess I'm fine with it as is. KISS for sure.

**Comment by ladyada** [comment]
thanks everyone!

**Comment by Dmole** [comment]
Thanks for the merge.

> ... example that goes with a standard humidity sensor would be nice...

Mixing protocols is not ideal so because sht31d and sgp30 both use I2C I think they are well matched.
Regardless I think all humidity sensors available from Adafruit output the same format so it should be minimal effort to make any of them work with the rh2gpm3 example.

> ...wondering about odd readings...

The raw eCO2 and VOC values are readable, so if a wrapper for that is added it could be used to eliminate wondering what the onchip compensation and calibration are up to.

**Pull request merged**
